project:
  type: website
  output-dir: docs

website:
  title: "practice_quarto"
  navbar:
    left:
    - text: "Resources"
      href: index_resources.qmd
    - text: "Packages"
      href: index_packages.qmd
    - text: "About"
      href: about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    page-layout: full

